### ISSUE TITLE
Interpolator setup

### ISSUE THREAD

**Issue by DominicDirkx** [tudat-team/tudat-multidoc#41]
Taken from issue #38 (added by @jo11he): Interpolators module could use some example snippets, else the use is not very clear, especially how to get an `InterpolatorSettings` object for the interpolator factory functions (here factory functions for the interpolator and the interpolator settings are on the same level, which is untypical for tudat and thus I think the snippets are necessary to clarify :) ) 

At the moment, explanation of the sructure of the interpolators is here:
https://tudat-space.readthedocs.io/en/latest/_src_user_guide/math/interpolators.html

Possible solutions:
* Moving this section: https://tudat-space.readthedocs.io/en/latest/_src_user_guide/math/interpolators.html#general-procedure into the API docs
* Adding a link to this tudat-space page in the module description
* Adding a link to this tudat-space page in one or more of the function docstrings

Your thoughts?

**Comment by gaffarelj** [comment]
> * Moving this section: https://tudat-space.readthedocs.io/en/latest/_src_user_guide/math/interpolators.html#general-procedure into the API docs

I think that this section is too detailed to have its place on the API docs, which in my opinion should be kept to the essential.

> * Adding a link to this tudat-space page in the module description
> * Adding a link to this tudat-space page in one or more of the function docstrings

I am in favor of doing both of these (since some users will probably overlook the link if it's only in the module description). And in addition to expanding the code snippets. I actually plan on adding snippets everywhere possible in the API docs at some points. But that is a very long-term (and quite low priority) in my task list.

**Comment by DominicDirkx** [comment]
Link to user guide added to interpolators module description.
